### ISSUE TITLE
What is key vector?

### ISSUE THREAD

**Issue by albertchristianto** [snowkylin/ntm#19]
Hi,

This is a great work. I have read your ppt and it is very clear. I also have read the paper. But I have a question. What is kt (key vector)? How to get key vector? because the paper doesn't mention it clearly.

Best regards,
Albert

**Comment by snowkylin** [comment]
For content-based addressing, key vector is the "content" that is compared to each vector M_t(i) by a similarity measure. See section 3.3.1 of the NTM paper for detail. It is one of the parameters of head and can be generated simply from the output of controller by some linear transformation. See line 29-47 and line 63 in `ntm_cell.py` for detail.

**Comment by albertchristianto** [comment]
Okay, thank you very much for the response and the information @snowkylin . I will check it.
best regards,
Albert
