### ISSUE TITLE
For different input sequence lengths is this keeping separate model ? 

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#3]
Here as I understood the code this keep one model for each sequence length . And will update the weights for each model separatly . Why don't we update the weights as in dynamic sequence to sequence-to-sequence model .

**Comment by snowkylin** [comment]
I use separate models sharing same variables, which is a bit brute but easy to program. It would be more elegant if something like `tf.nn.dynamic_rnn` can be applied here.

**Comment by shamanez** [comment]
thanks
