### ISSUE TITLE
Why an output of the certain time step do not use the current read vector?

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#4]
In Differential Neural Computers they first create a pre-output with the input and previous read vector then before writing the real output from the cell they add the current read vector also. Here as in the paper there is no addition of the current read vector . Am I right?

**Comment by snowkylin** [comment]
It should use the read vector, but in my implementation it is at the beginning of the model. Notice line 25 of `ntm_cell.py`:
> controller_input = tf.concat([x] + prev_read_vector_list, axis=1)

They are just equivalent. You can also view page 8 of [my slide](https://docs.google.com/presentation/d/1FqU7q-vWN9uV7sMRt9It9F_el9nIdqzBfMPm91hJ4B0/edit?usp=sharing) for a high-level understanding.
PS: there might be more than one read vectors so it is a list in my implementation (`prev_read_vector_list`)

**Comment by shamanez** [comment]
yeah I understand that. Any way to detect the current output you use previous time step's read vector right?  Then calculate the current time steps's read vector to fed in to the next time step and concatenate with the input.
But in the DNC I noticed they even use current time step's read vector.

**Comment by shamanez** [comment]
In this [line](https://github.com/snowkylin/ntm/blob/master/ntm/ntm_cell.py#L25) you use the previous time step's read vector.

**Comment by snowkylin** [comment]
Sorry that I missed the main point at first. I use read vectors in previous time step (`prev_read_vector_list`) at the beginning of the model, which is part of the controller's input (the arrow from `Read Heads` to `Controller` in Figure 1 of NTM paper). In NTM paper there is no direct connection between `Read Heads` and `External Output` in Figure 1, so I just follow this way and use the output generated by controller directly as the external output (after some linear transformation). However, you can concatenate `controller_output` with `read_vector_list` at the end of the model (around line 93), I guess that make sense too.

**Comment by shamanez** [comment]
Thanks
