### ISSUE TITLE
can you explain about the plotting read vectors ?

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#6]
When training you plot using the w_list in [this](https://github.com/snowkylin/ntm/blob/master/copy_task.py#L67) line. What do you plot here? 

is this the plot between , read weight list and write weight list?

**Comment by snowkylin** [comment]
`w_list` is the combination of read weights and write weights at a specific time step. When plotting the weights, the left part are the read weights and the right part are the write weights. The vertical axis means time step. You can find an example of result [here](https://github.com/snowkylin/ntm/blob/master/images/copy_task_head.png).

**Comment by shamanez** [comment]
what is the horizontal axis? Also, I don't understand the color pattern.

**Comment by snowkylin** [comment]
The horizontal axis is the location of the memory (you can divide it into two graphs, the left part is read weight and the right part is write weight). It is very similar to Figure 6 in the NTM paper.
