### ISSUE TITLE
How did you calculate the number of controller output parameters in MANN cell ? 

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#7]
In this [line](https://github.com/snowkylin/ntm/blob/master/ntm/mann_cell.py#L31) I don't understand the k_stragedy. Can you please explain it?  I understand you use part of the output to calculate the similarity and another one to aloha parameter. What is the other one?

**Comment by snowkylin** [comment]
In the original MANN paper, query key vector 'k' are used in both reading (eq 17) and writing (eq 23). You can set k_strategy='summary' if you want this way. However, in the NTM paper they are separated. If you set k_strategy='separate', the controller will generate a new add vector 'a' to replace the query vector 'k' in eq 23.

**Comment by shamanez** [comment]
Oh I never noticed it in the paper. I thought the k we are using is the same output from the controller which used to do content-based addressing as in the "summery" strategy. But when reading again they have used a separate one.
