### ISSUE TITLE
confusion when calculating the least used weight vector in MANN 

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#8]
In this [line](https://github.com/snowkylin/ntm/blob/master/ntm/mann_cell.py#L141) you have use self.num_head parameter. 

As I understood in the paper this stage we need to make the least value of the used vector to 1 and all other positions to zero. 

Here the top_k operation is giving, indices of the used vector in descending order of their values(since k=memory size). From that, we need to find the position which gives the smallest value and make it to 1 and others to zero.

But why we need num_head parameter?

**Comment by snowkylin** [comment]
Notice that "where n is set to equal the number of reads to memory." below equation (6) in the MANN paper. So not only one position will be set to 1.

**Comment by shamanez** [comment]
yeah yeah. If there are 4 read heads we need to have four ones in the used vectors and others in to zero. Sorry I missed that part. 

But what is the logic? Cannot find why they take this number?

**Comment by shamanez** [comment]
@snowkylin  can you please explain what does it mean to get least n indices which n is equal to the number of heads?

**Comment by snowkylin** [comment]
Considered that, if this is a conventional Turing Machine, we have 4 heads and want to store 4 different vectors into the memory by these heads, it means we need to write to 4 different positions in the memory, so we would like to find 4 proper slots (better if these slots are least used), make it empty and write data in them. NTM is more differentiable than TM, but the main point is roughly the same.

**Comment by shamanez** [comment]
Yeah I got it. Anyway it's more like giving a chance to use 4 empty slots for the 4 read heads. Anyway, it's like 4 read heads finds 4 different things they can write that down to 4 different slots. Otherwise, if they find something similar they have the option to write everything in to the same also. Am I correct?

**Comment by snowkylin** [comment]
Yes, I think the model just give the "chance" for the 4 heads to write to different slots without conflict by preparing 4 empty slots for them. However, it is still possible that some of them write to the same slot.
