### ISSUE TITLE
Why we need to set the least used memory location to zero in the memory matrix

### ISSUE THREAD

**Issue by shamanez** [snowkylin/ntm#9]
I understand what you did [here](https://github.com/snowkylin/ntm/blob/master/ntm/mann_cell.py#L75). It's like erasing the least used section from the memory before writing something new. But I couldn't find why we do it. 

Also  can you please elaborate why the find least used locations that equal to a number of reading heads?

**Comment by snowkylin** [comment]
I think it will be better if we clean the slots before writing data to them, or the data might be severely contaminated.
See my comment in issue#8 for the latter question.

**Comment by shamanez** [comment]
thanks.
